FEMS/Controllers/EmployeeProgressesController.cs
using FEMS.ControllerManager.EmployeeProgressesControllerManager;
using FEMS.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FEMS.Controllers
{
    public class EmployeeProgressesController : Controller
    {
        private EmployeeProgressesControllerManager EmployeeProgressesControllerManager;

        public EmployeeProgressesController()
        {
            EmployeeProgressesControllerManager = new EmployeeProgressesControllerManager();
        }

        [Authorize(Roles = "Admin")]
        // GET: EmployeeProgresses
        public ActionResult Index()
        {
            try
            {
                return View(EmployeeProgressesControllerManager.getAllProgress());
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: EmployeeProgresses/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                return View(EmployeeProgressesControllerManager.getProgress(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }


        //[Authorize(Roles = "Admin")]
        //// GET: EmployeeProgresses/Create
        //public ActionResult Create()
        //{
        //    ViewBag.month = EmployeeProgressesControllerManager.getMonth();
        //    return View();
        //}

        // POST: EmployeeProgresses/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(emp_progresses emp_progresses)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        int flag = EmployeeProgressesControllerManager.saveProgress(emp_progresses);
        //        if (flag == 1)
        //        {
        //            return RedirectToAction("Index");
        //        }
        //        else
        //        {
        //            //error message
        //        }
        //    }
        //    ViewBag.month = EmployeeProgressesControllerManager.getMonth();
        //    return View();
        //}


        [Authorize(Roles = "Admin")]
        // GET: EmployeeProgresses/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                ViewBag.month = EmployeeProgressesControllerManager.getMonth();
                return View(EmployeeProgressesControllerManager.getProgress(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }


        }

        // POST: EmployeeProgresses/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, emp_progresses emp_progresses)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int flag = EmployeeProgressesControllerManager.updateProgress(id, emp_progresses);
                    if (flag == 1)
                    {
                        return RedirectToAction("Index");
                    }
                }
                ViewBag.month = EmployeeProgressesControllerManager.getMonth();
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }



        }


        [Authorize(Roles = "Admin")]
        // GET: EmployeeProgresses/Delete/5
        public ActionResult Delete(int id)
        {   try
            {
                return View(EmployeeProgressesControllerManager.getProgress(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }

        }

        // POST: EmployeeProgresses/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, emp_progresses emp_progresses)
        {
           try
            {
                if (ModelState.IsValid)
                {
                    int flag = EmployeeProgressesControllerManager.deleteProgress(id, emp_progresses);
                    if (flag == 1)
                    {
                        return RedirectToAction("Index");
                    }
                }
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }

        }
    }
}

FEMS/Views/EmployeeProgresses/Delete.cshtml
@model FEMS.Database.emp_progresses

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee Progresses</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.emp_progress_working_hrs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_progress_working_hrs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp_progress_month_year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_progress_month_year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp_progress_nopay_days)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_progress_nopay_days)
        </dd>

     </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.emp_progress_id)
        @Html.HiddenFor(model => model.emp_progress_month_year)
        @Html.HiddenFor(model => model.emp_progress_nopay_days)
        @Html.HiddenFor(model => model.emp_progress_working_hrs)
        @Html.HiddenFor(model => model.emp_id)
        @Html.HiddenFor(model => model.project_id)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FEMS/Views/EmployeeProgresses/Details.cshtml
@model FEMS.Database.emp_progresses

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Employee Progresses</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.emp_progress_working_hrs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_progress_working_hrs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp_progress_month_year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_progress_month_year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp_progress_nopay_days)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_progress_nopay_days)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.emp_progress_id}) |
    @Html.ActionLink("Back to List", "Index")
</p>

FEMS/Views/EmployeeProgresses/Edit.cshtml
@model FEMS.Database.emp_progresses

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.emp_progress_id)
    @Html.HiddenFor(model => model.emp_progress_status)    
    @Html.HiddenFor(model => model.emp_id)
    @Html.HiddenFor(model => model.project_id)

    <div class="form-horizontal">
        <h4>Employee Progresses</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.emp_progress_working_hrs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emp_progress_working_hrs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emp_progress_working_hrs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emp_progress_month_year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emp_progress_month_year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emp_progress_month_year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emp_progress_nopay_days, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emp_progress_nopay_days, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emp_progress_nopay_days, "", new { @class = "text-danger" })
            </div>
        </div>

                <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FEMS/Views/EmployeeProgresses/Index.cshtml
@model IEnumerable<FEMS.Database.emp_progresses>

@using GridMvc.Html
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Employee Progress</h2>

<link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>
<script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>

<div class="code-cut">
    @Html.Grid(Model).Columns(Columns =>
{
    Columns.Add().RenderValueAs(e => e.employee.emp_fname + " " + e.employee.emp_lname).Titled("Full Name").SetWidth(150).Filterable(true);
    Columns.Add(e => e.project.project_name).Titled("Project Name").Filterable(true);
    Columns.Add(e => e.emp_progress_month_year).Titled("Month").Filterable(true);
    Columns.Add(e => e.emp_progress_nopay_days).Titled("No. of No Pay Days").Filterable(true);
    Columns.Add(e => e.emp_progress_working_hrs).Titled("No. of Working Hours").Filterable(true);

    if (User.IsInRole("Admin"))
    {
        Columns.Add()
    .Titled("")
    .SetWidth(15)
    .Filterable(true)
    .Sanitized(false)
    .Encoded(false)
    .RenderValueAs(e => Html.ActionLink("Edit", "Edit", "EmployeeProgresses", new { id = e.emp_progress_id }, htmlAttributes: new { @class = "btn btn-warning btn-primary btn-sm" })
    .ToHtmlString());

        Columns.Add()
            .Titled("")
            .SetWidth(15)
            .Filterable(true)
            .Sanitized(false)
            .Encoded(false)
            .RenderValueAs(e => Html.ActionLink("Details", "Details", "EmployeeProgresses", new { id = e.emp_progress_id }, htmlAttributes: new { @class = "btn btn-info btn-primary btn-sm" })
            .ToHtmlString());

        Columns.Add()
            .Titled("")
            .SetWidth(15)
            .Filterable(true)
            .Sanitized(false)
            .Encoded(false)
            .RenderValueAs(e => Html.ActionLink("Delete", "Delete", "EmployeeProgresses", new { id = e.emp_progress_id }, htmlAttributes: new { @class = "btn btn-danger btn-primary btn-sm" })
            .ToHtmlString());
    }

}).WithPaging(10).Sortable().Filterable()
</div>