FEMS/Controllers/ProjectProgressesController.cs
using FEMS.ControllerManager.ProjectProgressesControllerManager;
using FEMS.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FEMS.Controllers
{
    public class ProjectProgressesController : Controller
    {
        private ProjectProgressesControllerManager ProjectProgressesControllerManager;

        public ProjectProgressesController()
        {
            ProjectProgressesControllerManager = new ProjectProgressesControllerManager();
        }

        [Authorize(Roles = "Admin,Manager,Client")]
        // GET: ProjectProgresses
        public ActionResult Index()
        {
            try
            {
                return View(ProjectProgressesControllerManager.getAllProjectsProgreses());
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }

        }


        [Authorize(Roles = "Admin,Manager,Client")]
        // GET: ProjectProgresses/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                return View(ProjectProgressesControllerManager.getProjectProgress(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }

        }


        [Authorize(Roles = "Admin")]
        // GET: ProjectProgresses/Create
        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }


        }

        // POST: ProjectProgresses/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(project_progress progress)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ProjectProgressesControllerManager.saveProjectProgress(progress);
                }
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }

        }


        [Authorize(Roles = "Admin")]
        // GET: ProjectProgresses/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                return View(ProjectProgressesControllerManager.getProjectProgress(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // POST: ProjectProgresses/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, project_progress progress)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int flag = ProjectProgressesControllerManager.updateProjectProgress(id, progress);
                    if (flag == 1)
                    {
                        return RedirectToAction("Index");
                    }
                }
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: ProjectProgresses/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                return View(ProjectProgressesControllerManager.getProjectProgress(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }

        }

        // POST: ProjectProgresses/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, project_progress progress)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int flag = ProjectProgressesControllerManager.deleteProjectProgress(id, progress);
                    if (flag == 1)
                    {
                        return RedirectToAction("Index");
                    }
                }
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }

        }
    }
}

FEMS/Views/ProjectProgresses/Create.cshtml
@model FEMS.Database.project_progress

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project Progresses</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.no_of_tasks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.no_of_tasks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.no_of_tasks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.days_remaining, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.days_remaining, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.days_remaining, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.no_of_finished_tasks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.no_of_finished_tasks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.no_of_finished_tasks, "", new { @class = "text-danger" })
            </div>
        </div>

         <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FEMS/Views/ProjectProgresses/Delete.cshtml
@model FEMS.Database.project_progress

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project Progresses</h4>
    <hr />
    <dl class="dl-horizontal">
        
        <dt>
            @Html.DisplayNameFor(model => model.no_of_tasks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.no_of_tasks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.days_remaining)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.days_remaining)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.no_of_finished_tasks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.no_of_finished_tasks)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.progress_id)
        @Html.HiddenFor(model => model.no_of_finished_tasks)
        @Html.HiddenFor(model => model.no_of_tasks)
        @Html.HiddenFor(model => model.days_remaining)
        @Html.HiddenFor(model => model.project_id)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FEMS/Views/ProjectProgresses/Details.cshtml
@model FEMS.Database.project_progress

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>project_progress</h4>
    <hr />
    <dl class="dl-horizontal">
        
        <dt>
            @Html.DisplayNameFor(model => model.no_of_tasks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.no_of_tasks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.days_remaining)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.days_remaining)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.no_of_finished_tasks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.no_of_finished_tasks)
        </dd>

      </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FEMS/Views/ProjectProgresses/Edit.cshtml
 @model FEMS.Database.project_progress

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.progress_id)
    @Html.HiddenFor(model => model.project_id)

    <div class="form-horizontal">
        <h4>Project Progress</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.no_of_tasks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.no_of_tasks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.no_of_tasks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.days_remaining, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.days_remaining, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.days_remaining, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.no_of_finished_tasks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.no_of_finished_tasks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.no_of_finished_tasks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FEMS/Views/ProjectProgresses/Index.cshtml
@model IEnumerable<FEMS.Database.project_progress>

@using GridMvc.Html
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Project Progresses</h2>

<link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>
<script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>

<p>
    @Html.ActionLink("Create New", "Create", null, htmlAttributes: new { @class = "btn btn-success btn-primary btn-sm" })
</p>



<div class="code-cut">
    @Html.Grid(Model).Columns(Columns =>
{
    Columns.Add(p => p.project.project_name).Titled("Project Name").Filterable(true);
    Columns.Add(p => p.no_of_tasks).Titled("No of Tasks").Filterable(true);
    Columns.Add(p => p.no_of_finished_tasks).Titled("No of Finished Tasks").Filterable(true);
    Columns.Add(p => p.days_remaining).Titled("Days Remaining").Filterable(true);


    Columns.Add()
        .Titled("")
        .SetWidth(15)
        .Filterable(true)
        .Sanitized(false)
        .Encoded(false)
        .RenderValueAs(p => Html.ActionLink("Edit", "Edit", "ProjectProgresses", new { id = p.progress_id }, htmlAttributes: new { @class = "btn btn-warning btn-primary btn-sm" })
        .ToHtmlString());

    Columns.Add()
        .Titled("")
        .SetWidth(15)
        .Filterable(true)
        .Sanitized(false)
        .Encoded(false)
        .RenderValueAs(p => Html.ActionLink("Details", "Details", "ProjectProgresses", new { id = p.progress_id }, htmlAttributes: new { @class = "btn btn-info btn-primary btn-sm" })
        .ToHtmlString());

    Columns.Add()
        .Titled("")
        .SetWidth(15)
        .Filterable(true)
        .Sanitized(false)
        .Encoded(false)
        .RenderValueAs(p => Html.ActionLink("Delete", "Delete", "ProjectProgresses", new { id = p.progress_id }, htmlAttributes: new { @class = "btn btn-danger btn-primary btn-sm" })
        .ToHtmlString());

}).WithPaging(10).Sortable().Filterable()
</div>